# Generated by Django 5.1.4 on 2025-04-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('line', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(default=15.117421421361927)),
                ('longitude', models.FloatField(default=104.90284046686651)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='exercises/')),
                ('method', models.TextField()),
                ('equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('sets', models.CharField(max_length=255)),
                ('muscle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('tel_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vfit.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vfit.product')),
            ],
        ),
        migrations.CreateModel(
            name='RentalRecord',
            fields=[
                ('order_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_price', models.IntegerField()),
                ('amount', models.IntegerField(default=1)),
                ('ren_time', models.IntegerField()),
                ('get_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('renting', 'Renting'), ('return', 'Return'), ('overdue', 'Overdue'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('overdue_time', models.IntegerField(default=0)),
                ('time_remaining', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='vfit.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_records', to='vfit.users')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=50)),
                ('rental_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='vfit.rentalrecord')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vfit.users'),
        ),
        migrations.CreateModel(
            name='buy_record',
            fields=[
                ('order_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('buy_date', models.DateField(auto_now_add=True)),
                ('get_date', models.DateField()),
                ('total_price', models.IntegerField()),
                ('is_received', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vfit.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vfit.users')),
            ],
        ),
    ]
