# Generated by Django 5.1.4 on 2025-04-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
