# Generated by Django 5.1.4 on 2025-04-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
